services:
  backend:
    build: ./procuraBackend
    container_name: orka_reducida_backend
    environment:
      DATABASE_URL: "postgresql://OrDbUser2024:OrStrongPass_69!2024@69.6.234.185:5432/orka_reducida_db?schema=public"
      JWT_SECRET: "orka-reducida-secret-key-2026"
      JWT_EXPIRES_IN: "24h"
      PORT: "3006"
      NODE_ENV: "production"
    ports:
      - "3006:3006"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - orka_reducida_network

  frontend:
    build:
      context: ./procuraFrontend
      dockerfile: Dockerfile
    container_name: orka_reducida_frontend
    depends_on:
      - backend
    ports:
      - "5174:80"
    restart: unless-stopped
    networks:
      - orka_reducida_network

networks:
  orka_reducida_network:
    driver: bridge